"""
Pydantic models for DNS threat detection results.
Covers DNS tunneling, DGA domains, and suspicious DNS patterns.
"""
from typing import Optional
from pydantic import BaseModel, Field


class DnsTunnelingResult(BaseModel):
    """
    Result from DNS tunneling detection analysis.
    DNS tunneling uses DNS queries/responses to exfiltrate data or establish C2 channels.
    """

    domain: str = Field(..., description="Suspicious domain name")
    src_ip: str = Field(..., description="Source IP making queries")

    # Query characteristics
    query_count: int = Field(..., description="Number of queries to this domain")
    unique_subdomains: int = Field(..., description="Number of unique subdomains queried")

    # Entropy analysis (indicates randomness/data encoding in subdomain)
    avg_subdomain_entropy: float = Field(..., description="Average Shannon entropy of subdomains")
    max_subdomain_entropy: float = Field(..., description="Maximum subdomain entropy observed")
    avg_subdomain_length: float = Field(..., description="Average subdomain length in characters")
    max_subdomain_length: int = Field(..., description="Maximum subdomain length observed")

    # Query type analysis
    txt_record_queries: int = Field(default=0, description="Count of TXT record queries")
    nxdomain_responses: int = Field(default=0, description="Count of NXDOMAIN responses")
    unusual_query_types: list[str] = Field(default_factory=list, description="Unusual query types observed")

    # Data transfer estimation
    estimated_bytes_exfiltrated: Optional[int] = Field(None, description="Estimated bytes exfiltrated via DNS")

    # Scoring
    tunneling_score: float = Field(..., ge=0.0, le=100.0, description="DNS tunneling likelihood score (0-100)")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Detection confidence (0-1)")

    # Explainability
    reasons: list[str] = Field(default_factory=list, description="Why this was flagged as tunneling")

    # MITRE ATT&CK mapping
    mitre_techniques: list[str] = Field(
        default_factory=list,
        description="MITRE ATT&CK technique IDs"
    )

    # Timeline
    first_seen: float = Field(..., description="First query timestamp")
    last_seen: float = Field(..., description="Last query timestamp")
    time_span_seconds: float = Field(..., description="Total time span of observations")


class DgaResult(BaseModel):
    """
    Result from DGA (Domain Generation Algorithm) detection.
    DGA domains are algorithmically generated by malware for C2 communication.
    """

    domain: str = Field(..., description="Suspicious domain name")
    src_ip: str = Field(..., description="Source IP making queries")

    # Lexical analysis
    domain_entropy: float = Field(..., description="Shannon entropy of domain name")
    consonant_ratio: float = Field(..., description="Ratio of consonants to vowels")
    digit_ratio: float = Field(..., description="Ratio of digits in domain")
    bigram_score: float = Field(..., description="Bigram frequency score (lower = less English-like)")
    meaningful_parts: int = Field(..., description="Number of meaningful word parts found")

    # Query characteristics
    query_count: int = Field(..., description="Number of queries to this domain")
    nxdomain_count: int = Field(..., description="Number of NXDOMAIN responses")
    success_count: int = Field(..., description="Number of successful resolutions")

    # TLD analysis
    tld: str = Field(..., description="Top-level domain")
    tld_common: bool = Field(..., description="Is TLD commonly used")

    # Scoring
    dga_score: float = Field(..., ge=0.0, le=100.0, description="DGA likelihood score (0-100)")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Detection confidence (0-1)")

    # Explainability
    reasons: list[str] = Field(default_factory=list, description="Why this was flagged as DGA")

    # MITRE ATT&CK mapping
    mitre_techniques: list[str] = Field(
        default_factory=list,
        description="MITRE ATT&CK technique IDs"
    )

    # Timeline
    first_seen: float = Field(..., description="First query timestamp")
    last_seen: float = Field(..., description="Last query timestamp")


class DnsFastFluxResult(BaseModel):
    """
    Result from fast-flux DNS detection.
    Fast-flux uses rapidly changing DNS records to evade detection and takedowns.
    """

    domain: str = Field(..., description="Domain exhibiting fast-flux behavior")

    # IP rotation characteristics
    unique_ips: int = Field(..., description="Number of unique IPs returned")
    ip_list: list[str] = Field(..., description="List of IPs observed")
    avg_ttl: float = Field(..., description="Average TTL (seconds)")
    min_ttl: float = Field(..., description="Minimum TTL observed")

    # Change rate analysis
    query_count: int = Field(..., description="Number of DNS queries")
    ip_changes_per_hour: float = Field(..., description="Rate of IP address changes")
    distinct_asns: int = Field(..., description="Number of distinct ASNs for IPs")
    distinct_countries: int = Field(..., description="Number of distinct countries for IPs")

    # Scoring
    fast_flux_score: float = Field(..., ge=0.0, le=100.0, description="Fast-flux likelihood score (0-100)")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Detection confidence (0-1)")

    # Explainability
    reasons: list[str] = Field(default_factory=list, description="Why this was flagged as fast-flux")

    # MITRE ATT&CK mapping
    mitre_techniques: list[str] = Field(
        default_factory=list,
        description="MITRE ATT&CK technique IDs"
    )

    # Timeline
    first_seen: float = Field(..., description="First query timestamp")
    last_seen: float = Field(..., description="Last query timestamp")
    time_span_seconds: float = Field(..., description="Total time span of observations")


class SuspiciousDnsPattern(BaseModel):
    """
    Result from general suspicious DNS pattern detection.
    Catches unusual DNS behavior that doesn't fit specific categories.
    """

    pattern_type: str = Field(..., description="Type of suspicious pattern detected")
    domain: Optional[str] = Field(None, description="Domain involved (if applicable)")
    src_ip: str = Field(..., description="Source IP exhibiting pattern")

    # Pattern-specific metrics
    query_count: int = Field(..., description="Number of queries involved")
    unique_domains: int = Field(default=0, description="Number of unique domains")

    # Anomaly indicators
    anomaly_indicators: list[str] = Field(default_factory=list, description="Specific anomalies detected")

    # Scoring
    suspicion_score: float = Field(..., ge=0.0, le=100.0, description="Suspicion score (0-100)")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Detection confidence (0-1)")

    # Explainability
    reasons: list[str] = Field(default_factory=list, description="Why this was flagged")

    # MITRE ATT&CK mapping
    mitre_techniques: list[str] = Field(
        default_factory=list,
        description="MITRE ATT&CK technique IDs"
    )

    # Timeline
    first_seen: float = Field(..., description="First observation timestamp")
    last_seen: float = Field(..., description="Last observation timestamp")


class DnsThreatSummary(BaseModel):
    """
    Summary of all DNS threats detected in the dataset.
    """

    total_queries_analyzed: int = Field(..., description="Total DNS queries analyzed")

    # Detection counts
    tunneling_detections: int = Field(default=0, description="Number of tunneling detections")
    dga_detections: int = Field(default=0, description="Number of DGA detections")
    fast_flux_detections: int = Field(default=0, description="Number of fast-flux detections")
    other_patterns: int = Field(default=0, description="Number of other suspicious patterns")

    # Top threats
    top_tunneling: list[DnsTunnelingResult] = Field(default_factory=list, description="Top tunneling threats")
    top_dga: list[DgaResult] = Field(default_factory=list, description="Top DGA threats")
    top_fast_flux: list[DnsFastFluxResult] = Field(default_factory=list, description="Top fast-flux threats")
    top_patterns: list[SuspiciousDnsPattern] = Field(default_factory=list, description="Top other patterns")

    # Analysis metadata
    analysis_start: float = Field(..., description="Analysis start timestamp")
    analysis_end: float = Field(..., description="Analysis end timestamp")
    data_time_range_start: Optional[float] = Field(None, description="First DNS query timestamp")
    data_time_range_end: Optional[float] = Field(None, description="Last DNS query timestamp")
